### ISSUE TITLE
number of characters ignored for incoming texts

### ISSUE THREAD

**Issue by PescheHelfer** [JonnoFTW/SMS-Morse#1]
When an actual text arrives, only the first few characters (5) are translated into morsecode. In settings, I set the number of characters to play to 100. It seems like this setting works for the input field but not for incoming texts.

**Comment by JonnoFTW** [comment]
Do you have the "play sender phone number" checked? If selected it only plays the number and not the full message.

**Comment by PescheHelfer** [comment]
Nope, this option is not checket - and it's the first few characters of the message that is morsed.

**Comment by JonnoFTW** [comment]
Okay, I see where the problem is. The `SettingsActivity` isn't correctly setting the preference value and the fallback of 4 characters is being used during playback. I'll look into it.

**Comment by JonnoFTW** [comment]
I've submitted a fix to the Play Store, please upgrade and let me know.

**Comment by PescheHelfer** [comment]
Thanks a lot! It's working almost perfectly now. Under some circumstances (but not always) the message is played twice, now. But that does not bother me :)

**Comment by JonnoFTW** [comment]
Fixed in 9b7eeeb9f8e02601a56ea3e17bacb423436ccbd4
